import Head from "next/head";


interface LayoutProps {
  children: React.ReactNode;
  title?: string;
}

function Layout({ children, title }: LayoutProps): JSX.Element {
  

  return (
    <div>
      <Head>
        <title>GAME (Valorant) {title ? ` | ${title}` : ""} </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
        <div>{children}</div>
      
    </div>
  );
}

export default Layout;